### ISSUE TITLE
Groups and Permissions for Collectives

### ISSUE THREAD

**Issue by marcondag** [debtcollective/discourse-seed#3]
Per the requirements, collectives are only to be visible to the people who are members of them. To accomplish this we will create a group per collective and assign it the permissions to restrict only members of that group to be able to view the collective the group is named after. For example:

Group = fp-student-debt
Collective = For Profit Student Debt Collective
Permission = only members of fp-student-debt group may see the For Profit Student Debt Collective and its posts

**Comment by shoshber** [comment]
I think this is done
